package com.qf.pojo;
// Generated 2017-9-10 19:40:48 by Hibernate Tools 5.2.1.Final

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer sid;
	private String sname;
	private String sdesc;

	public Student() {
	}

	public Student(String sname, String sdesc) {
		this.sname = sname;
		this.sdesc = sdesc;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSdesc() {
		return this.sdesc;
	}

	public void setSdesc(String sdesc) {
		this.sdesc = sdesc;
	}

}
